version: "3.9"

services:    
   filebeat:
      image: docker.elastic.co/beats/filebeat:7.14.1-amd64
      labels: 
         author: "Houston Santos - houston_santos@hotmail.com"
      container_name: filebeat
      user: root
      command: filebeat -e -strict.perms=false
      healthcheck:
         test: filebeat -strict.perms=false test config
      restart: on-failure
      volumes:
         - ./beats/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
         - /var/lib/docker/containers:/var/lib/docker/containers:ro
         - /var/run/docker.sock:/var/run/docker.sock:ro
      ports: 
         - 2055:2055/udp
      networks:
         - elastic

   #metricbeat:
   #   image: docker.elastic.co/beats/metricbeat:7.14.1-amd64
   #   labels: 
   #      author: "Houston Santos - houston_santos@hotmail.com"
   #   container_name: metricbeat
   #   user: root
   #   #command: filebeat -e -strict.perms=false
   #   #healthcheck:
   #      #test: filebeat test config
   #      #test: filebeat -strict.perms=false test config
   #   restart: on-failure
   #   #volumes:
   #      #- ./beats/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
   #   #ports: 
   #      #- 2055:2055/udp
   #   networks:
   #      - elastic
   #      - databases

#volumes: 
   # filebeat:

networks: 
   elastic:
      external: true
   databases:
      external: true